import { RailConstants } from "./types";

export const SIMULATOR_RAIL_CONSTANTS: Readonly<RailConstants> = {
  GAUGE: 1,
  CURVE_RADIUS: 12,
  STRAIGHT_LENGTH: 12,
  HALF_STRAIGHT_LENGTH: 6,
  QUARTER_STRAIGHT_LENGTH: 3,
  SIXTH_STRAIGHT_LENGTH: 2,
  MINI_BLOCK_PILLAR_HEIGHT: 1,
  PASSAGE_HEIGHT: 4,
  DOUBLE_TRACK_SPACING: 1,
  STATION_SPACING: 1,
  ACTUAL_CIRCLE_DEGREES: 8,
  CURVE_ARC_COUNT: 8,
};
